services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8009 --reload"
    ports:
      - "8009:8009"
